[package]
name = "rust-screenshots"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
rdev = {version = "0.5.3", features = ["unstable_grab"]}
xcap = "0.0.10"
screenshots = "0.8.5 "